### ISSUE TITLE
[Improvement] [Feature request] Get amount of reports of a user/team member

### ISSUE THREAD

**Issue by CodingDavid8** [andrewthetechie/geekbot-api-py#5]
Would be great to have a high level function to get the amount of reports of the users from 

Basically something like the leaderboard in the Geekbot Dashboard:
![grafik](https://user-images.githubusercontent.com/54584421/137873803-ca6c03d1-8558-4bfb-8111-7f5ab4101388.png)

Would be great to automize it so that I can share the leaderboard publicly in our associated Slack channel :D

The Standups Client could get something like this:
`get_team_report_amount(standup_id: str, start_date: datetime, end_date: datetime, user_id: Optional[str]) -> dict[User, int]` 

where user_id is an optional parameter to get only the report amount of a specific user and the returned value is a dictionary of the users and their report submissions. The parameters start_ and end_date represent the range within the amount should be counted.

**Comment by andrewthetechie** [comment]
Hi @CodingDavid8,

I apologize for the long gap in replying to this issue. Thank you for submitting your feature request. I appreciate your interest in our project and your dedication to making it better.

After carefully reviewing your request, I have determined that it is not appropriate for inclusion in geekbot-api-py. The feature you are proposing belongs in an application's code rather than in the library.

My focus is to provide an easy-to-use library that represents the geekbot api. To achieve this goal, I need to keep the library's scope focused and avoid including features that are not expressed by the Geekbot API itself.

If you have any other ideas or suggestions for the library, please don't hesitate to submit them, and I will be happy to consider them.
